[package]
name        = "i3quitdialog"
version     = "0.1.7"
authors     = ["Rodrigo Cacilhας <montegasppa@cacilhas.info"]
license     = "BSD-3-Clause"
readme      = "README.md"
homepage    = "https://github.com/cacilhas/microcli/tree/master/i3quitdialog"
repository  = "https://github.com/cacilhas/microcli/tree/master/i3quitdialog"
keywords    = ["gui", "i3wm", "linux"]
category    = "gui"
description = "A simple quit dialog for i3wm."
edition     = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = "s"
debug = false
rpath = false
strip = true

[dependencies]
fltk = "^1.3"
i3_ipc = "^0.16"
users = "^0.11"
