[package]
name        = "brightcli"
version     = "0.1.6"
authors     = ["Rodrigo Montegasppα Cacilhας <montegasppa@cacilhas.info"]
license     = "BSD-3-Clause"
readme      = "README.md"
homepage    = "https://github.com/cacilhas/microcli/tree/master/brightcli"
repository  = "https://github.com/cacilhas/microcli/tree/master/brightcli"
keywords    = ["cli", "brightness", "linux"]
category    = "command-line-utilities"
description = "Util to change monitor brightness."
edition     = "2021"

[dependencies]
